### ISSUE TITLE
02/14/2024: Failed to load resource: the server responded with a status of 503 (Service Unavailable)

### ISSUE THREAD

**Issue by Filename99** [benjitrosch/whowouldwin#1]
![image](https://github.com/benjitrosch/whowouldwin/assets/71535927/5ee1c663-99d7-4fab-9191-44098b5f1f83)

**Comment by benjitrosch** [comment]
@Filename99 thanks for reporting this. Seems that the OpenAI API key being used for the site has reached it's monthly limit already. I'll have to push up a change to allow users to provide their own key before bringing the site back up. Stay tuned!

**Comment by benjitrosch** [comment]
@Filename99 this should be fixed with 18c13135ecdb34b3a4c89a7dbbed1b02c31a57cf. To make a long story short, I've downgraded from GPT4 to GPT3.5 to save money so the $120 monthly quota doesn't get hit as quickly. Also, I've exposed the out of funds error message to the client side so people know why their prompts aren't working.

**Comment by Filename99** [comment]
It was very unusual to see a small project done in a couple of hours to get a "bug fix". Usually they get abandoned, so I've never seen anything like this. Thank you very much!
